---
title: "transmission_metrics2"
author: "Paul Taconet"
date: "20/09/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) #set t
```

```{r packages}
library(ggplot2)
library(scales)
library(sf)
library(DBI)
library(RSQLite)
library(dplyr)
library(tidyr)
library(purrr)
library(rlang)
library(patchwork)
library(plotly)
library(htmlwidgets)
#library(kable)
library(kableExtra)
library(mapview)
library(stringr)
library(emo)
library(facetscales)
library(ggmap)
```

```{r db_connect}
# connect to database
code_pays = "CI"

path_to_db <- "data/react_db/react_db.gpkg"
react_gpkg <- DBI::dbConnect(RSQLite::SQLite(),dbname = path_to_db)

periodes_interv <-  dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% dplyr::select(-geom)
villages_intervs <-   dbReadTable(react_gpkg, 'recensement_villages_l1') %>% dplyr::select(-geom)

villages_missions_interv <- periodes_interv %>%
  left_join(villages_intervs, by = "codevillage") %>%
  dplyr::select(codevillage,intervention,nummission,period_interv) %>%
  mutate(nummission = as.numeric(nummission))

googlesheets4::sheets_deauth()
prediction_vars <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1dIeSOa2WinXvOQGLmIjA0gFdsHnb6zMMsDME-G5pyMc/edit?usp=sharing", sheet = "var_explication", col_types="c")

sf_villages <- st_read(path_to_db, 'recensement_villages_l1', stringsAsFactors = F) %>%
  filter(codepays==code_pays,!is.na(intervention)) %>%
  st_buffer(0.02)

library(geofacet)
grid_bf <- grid_auto(sf_villages, names = "nomvillage", codes = "codevillage", seed = 4) 

if(code_pays=="BF"){
  species <- c( "An.funestus_ss", "An.coluzzii", "An.gambiae_ss")
  col_filter <- "pcr_espece"
} else if(code_pays=="CI"){
  species <- c("An.funestus", "An.gambiae s.l.")
  col_filter <- "especeanoph"
}

```

## Timeline of the project

```{r }


 
fun_map <- function(codepayss,tit){
 ## map
 roi <- sf::st_read(path_to_db,"contexte_frontieresreact") %>% 
     filter(codepays == codepayss) %>%
     sf::st_transform(4326) %>%
     sf::st_bbox() %>%
     as.numeric()
  
  myLocation <- c(roi[1], roi[2], roi[3], roi[4])
  myMap <- get_map(location=myLocation, source="osm",crop=FALSE)
  
  if(codepayss=="BF"){
    n_mission <- 7
    n_vil <- 27
    date_interv <- 3
  } else if(codepayss=="CI") {
    n_mission <- 8
    n_vil <- 28
    date_interv <- 4
  }
    villages <- dbReadTable(react_gpkg, 'recensement_villages_l1') %>%
    dplyr::select(-geom) %>%
    dplyr::filter(!is.na(intervention),codepays == codepayss) %>%
      filter(!(codevillage %in% c("TAK","MOR","KAG","NOK"))) %>%
      mutate(intervention = case_when(intervention == "Ctrle" ~ "LLIN",
                                      intervention == "IEC" ~ "LLIN + Information, Education, Communication",
                                      intervention == "IRS" ~ "LLIN + Indoor residual spraying",
                                      intervention == "IVM" ~ "LLIN + Ivermectine",
                                       intervention == "Larvicide" ~ "LLIN + Larvicide")) %>%
      dplyr::select(codevillage,codepays,intervention,X,Y) %>%
      slice(rep(1:n(), each = n_mission)) %>%
      mutate(nummission = rep(seq(1,n_mission) , n_vil)) %>%
      mutate(intervention = ifelse(nummission <= date_interv,"LLIN",intervention)) %>%
      add_row(codevillage = "b", codepays=ifelse(codepayss=="BF","CI","BF"),intervention=ifelse(codepayss=="BF","LLIN + Larvicide","LLIN + Ivermectine"),X=0,Y=0,nummission=1)
  
  
  m <- ggmap(myMap) + geom_point(aes(x = X, y = Y, shape = intervention), data = villages, size = 2)  + facet_grid(.~nummission) + labs(shape = "Vector control tool") + theme(legend.position = ifelse(codepayss=="BF", 'bottom','none'),axis.title.x=element_blank(),axis.title.y=element_blank()) + ggtitle(tit)
  
  return(m)
}

m1 <- fun_map("CI","Korhogo (IC)")
m2 <- fun_map("BF","Diébougou (BF)")

m <- m1/m2 + plot_annotation(title = 'Vector control', subtitle = "Vector control tool in use for each village and entomological survey")

  ggsave(filename="vc_vctool.png",plot=m,path="/home/ptaconet/phd/articles/article2",dpi = 300)
  
  #  library(tmaptools)
 #  library(tmap)
  # osm <- read_osm(roi, type = "stamen-terrain")
  # osm = as(osm,"Raster")
  # 
  # sf_villages <- st_read(path_to_db, 'recensement_villages_l1', stringsAsFactors = F) %>%
  #  filter(codepays==codepayss[i],!is.na(intervention))
  # 
  # p = tm_shape(osm) + tm_rgb() + tm_shape(sf_villages) + tm_symbols(col = "black", size = 0.5) + tm_scale_bar()

dates_entomo <- dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% 
  dplyr::select(-geom) %>%
  group_by(nummission, codepays) %>%
  summarise(date = mean(as.Date(date_capture))) %>%
  mutate(nummission = as.numeric(nummission)) %>%
  filter(nummission < 10) %>%
  rename(survey_num = nummission) %>%
  as_tibble() %>%
  mutate(Surveys = "Anopheles behaviour survey")

dates_recensement <- dbReadTable(react_gpkg, 'recensement_menages_l0') %>% 
  dplyr::select(-geom) %>%
  group_by(codepays) %>%
  summarise(date = min(as.Date(dateenq))) %>%
  mutate(survey_num = NA) %>%
  mutate(Surveys = "Human census")

  #mutate(Surveys = "Human + animal census")

dates_cpthumain <- dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>% 
  dplyr::select(-geom) %>%
  group_by(codepays,survey) %>%
  rename(survey_num = survey) %>%
  summarise(date = mean(as.Date(dateenquete))) %>%
  as_tibble() %>%
  mutate(survey_num=case_when(codepays=="BF" ~ survey_num,
                              codepays=="CI" & survey_num==2 ~ 1,
                              codepays=="CI" & survey_num==3 ~ 2)) %>%
  mutate(Surveys = "Human behaviour survey")

dates_llin <- data.frame(codepays=c("BF","CI"),date=c(as.Date("2016-07-01"),as.Date("2017-06-01")), stringsAsFactors = F)%>%
  mutate(Surveys = "LLIN distribution", survey_num = NA)

dates_add_vc <- dbReadTable(react_gpkg, 'recensement_villages_l1') %>% dplyr::select(-geom) %>%
  filter(intervention %in% c("IRS","IVM","IEC","Larvicide")) %>%
    group_by(codepays) %>%
   summarise(date = mean(as.Date(date_debut_interv))) %>%
    as_tibble() %>%
  mutate(Surveys = "Implementation of complementary VC strategy", survey_num = NA)

dates_epi_active <- dbReadTable(react_gpkg, 'epidemio_active_l1') %>% 
  dplyr::select(-geom) %>%
  group_by(codepays,codenquete) %>%
  rename(survey_num = codenquete) %>%
  summarise(date = mean(as.Date(datenquete))) %>%
  as_tibble() %>%
  mutate(Surveys = "Epidemio - active")

dates_to_plot <- rbind(dates_entomo,dates_recensement,dates_cpthumain,dates_epi_active,dates_llin,dates_add_vc) %>%
  mutate(Surveys = forcats::fct_relevel(Surveys, c("Human census","Anopheles behaviour survey","Human behaviour survey","Epidemio - active","LLIN distribution","Implementation of complementary VC strategy"))) %>%
  filter(Surveys %in% c("Human census","Anopheles behaviour survey","Human behaviour survey","Implementation of complementary VC strategy","LLIN distribution")) %>% 
  mutate(position = case_when(codepays=="BF" & Surveys %in% c("Human census","Anopheles behaviour survey","Human behaviour survey","Epidemio - active") ~ 0.3,
                              codepays=="CI" & Surveys %in% c("Human census","Anopheles behaviour survey","Human behaviour survey","Epidemio - active") ~ -0.3,
                              codepays=="BF" & Surveys %in% c("Implementation of complementary VC strategy","LLIN distribution") ~ 0.1,
                              codepays=="CI" & Surveys %in% c("Implementation of complementary VC strategy","LLIN distribution") ~ -0.1,
                              )) %>%
  mutate(direction = ifelse(codepays=="BF" , 1, -1))

text_offset <- 0.2

# Let's use the absolute value since we want to add the text_offset and increase space away from the scatter points 
absolute_value<-(abs(dates_to_plot$position)) 
text_position<- absolute_value + text_offset

# Let's keep the direction above or below for the labels to match the scatter points
dates_to_plot$text_position<- text_position * dates_to_plot$direction 


month_buffer <- 1 

month_date_range <- seq(min(dates_to_plot$date), max(dates_to_plot$date) + months(month_buffer), by='month')

# We are adding one month before and one month after the earliest and latest milestone in the clinical course.
## We want the format of the months to be in the 3 letter abbreviations of each month.
lct <- Sys.getlocale("LC_TIME"); Sys.setlocale("LC_TIME", "C")
month_format <- format(month_date_range, '%b') 
month_df <- data.frame(month_date_range, month_format)


year_date_range <- seq(min(dates_to_plot$date) - months(month_buffer), max(dates_to_plot$date) + months(month_buffer), by='year')

# We will only show the years for which we have a december to january transition.
year_date_range <- as.Date(
    intersect(
        lubridate::ceiling_date(year_date_range, unit="year"),
        lubridate::floor_date(year_date_range, unit="year")),  
        origin = "1970-01-01") 

# We want the format to be in the four digit format for years.
year_format <- format(year_date_range, '%Y') 
year_df <- data.frame(year_date_range, year_format) %>%
  add_row(year_date_range=as.Date("2016-08-01"),year_format="2016") %>%
  add_row(year_date_range=as.Date("2018-01-01"),year_format="2018")

library("ggsci")
# Create timeline coordinates with an x and y axis
 timeline_plot <- ggplot(dates_to_plot,aes(x=date, y= position, col=Surveys)) +
   theme_classic() +
   geom_text(aes(y=text_position,label=survey_num)) + 
   geom_hline(yintercept=0, color = "black", size=0.3) +
   geom_segment(data=dates_to_plot, aes(y=position,yend=0,xend=date), color='black', size=0.2) +
   geom_point(aes(y=position), size=3) + 
   theme(axis.line.y=element_blank(),
                  axis.text.y=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  axis.ticks.y=element_blank(),
              axis.text.x =element_blank(),
                  axis.ticks.x =element_blank(),
                  axis.line.x =element_blank(),
                legend.position = "bottom"
                 ) + 
   guides(col=guide_legend(nrow=2,byrow=TRUE)) +
   labs(col = "Event") + 
   geom_text(data=month_df, aes(x=month_date_range,y=-0.15,label=month_format),size=3.5,vjust=0.5, color='black', angle=90) +
   geom_text(data=year_df, aes(x=year_date_range+30,y=0.08,label=year_format, fontface="bold"),size=3.5, color='black') + 
   #scale_color_manual(values = c("black","blue","red")) +
   scale_color_brewer(palette = "Dark2") +
   annotate(geom="label", x=min(dates_to_plot$date)-30, y=0.2, label="BF")  +
   annotate(geom="label", x=min(dates_to_plot$date)-30, y=-0.2, label="IC") 

# Print plot
timeline_plot


 timeline_plot_bf <- ggplot(dates_to_plot %>% filter(codepays == "BF"),aes(x=date, y= 1, col=Surveys, label=survey_num)) +
   theme_classic() +
   geom_text(vjust=10) + 
   geom_hline(yintercept=0, color = "black", size=0.3) +
   geom_segment(data=dates_to_plot %>% filter(codepays == "BF"), aes(y=position,yend=0,xend=date), color='black', size=0.2) +
   geom_point(aes(y=position), size=3) + 
   theme(axis.line.y=element_blank(),
                  axis.text.y=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  axis.ticks.y=element_blank(),
                  axis.text.x =element_blank(),
                  axis.ticks.x =element_blank(),
                  axis.line.x =element_blank(),
                  legend.position = "bottom",
                  legend.text=element_text(size=10)
                 ) + 
     # guides(col=guide_legend(nrow=2,byrow=TRUE)) +
   labs(col = "") + 
   geom_text(data=month_df, aes(x=month_date_range,y=-0.15,label=month_format),size=3.5,vjust=0.5, color='black', angle=90) +
   geom_label(data=year_df, aes(x=year_date_range+30,y=0.08,label=year_format, fontface="bold"),size=3.5, color='black') + 
   #scale_color_manual(values = c("black","blue","red")) +
   #scale_color_brewer(palette = "Dark2")
    scale_color_jco()

 timeline_plot_ci <- ggplot(dates_to_plot %>% filter(codepays == "CI"),aes(x=date, y= 1, col=Surveys, label=survey_num)) +
     theme_classic() +
     geom_text(vjust=10) + 
     geom_hline(yintercept=0, color = "black", size=0.3) +
     geom_segment(data=dates_to_plot %>% filter(codepays == "CI"), aes(y=0,yend=-position,xend=date), color='black', size=0.2) +
     geom_point(aes(y=-position), size=3) + 
     theme(axis.line.y=element_blank(),
           axis.text.y=element_blank(),
           axis.title.x=element_blank(),
           axis.title.y=element_blank(),
           axis.ticks.y=element_blank(),
           axis.text.x =element_blank(),
           axis.ticks.x =element_blank(),
           axis.line.x =element_blank(),
           legend.position = "bottom",
           legend.text=element_text(size=10)
     ) + 
      #guides(col=guide_legend(nrow=2,byrow=TRUE)) +
     labs(col = "") + 
     geom_text(data=month_df, aes(x=month_date_range,y=-0.15,label=month_format),size=3.5,vjust=0.5, color='black', angle=90) +
     geom_label(data=year_df, aes(x=year_date_range+30,y=0.08,label=year_format, fontface="bold"),size=3.5, color='black') + 
     #scale_color_manual(values = c("black","blue","red")) +
     #scale_color_brewer(palette = "Dark2")
    scale_color_jco()

timeline_plot_ci + timeline_plot_bf + plot_layout(guides = 'collect') & theme(legend.position='bottom')
```

## Presence / absence of bites


```{r }


df <-  dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter((!!sym(col_filter)) %in% species) %>%
  filter(nummission<10, codepays == code_pays) %>%
  dplyr::select(idpostedecapture,nummission,(!!sym(col_filter))) %>%
  unique() %>%
  mutate(status = "presence") %>%
  pivot_wider(names_from = (!!sym(col_filter)),  values_from = status)

entomo_csh_metadata_l1_ext <- dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% 
  dplyr::select(-geom) %>%
  mutate(nummission = as.numeric(nummission)) %>%
  filter(nummission<10, codepays == code_pays) %>%
  dplyr::select(idpointdecapture, codevillage, nummission,date_capture, codepays, period_interv) %>%
  mutate(nummission = as.numeric(nummission)) %>%
  mutate(idpostedecapture = paste0(idpointdecapture,"e"))

entomo_csh_metadata_l1_int <- entomo_csh_metadata_l1_ext %>% 
  mutate(idpostedecapture = paste0(idpointdecapture,"i"))

df_plot_presence <- rbind(entomo_csh_metadata_l1_ext,entomo_csh_metadata_l1_int) %>%
  left_join(df) %>%
  replace(is.na(.), "Absence") %>%
  pivot_longer(species, names_to = "species", values_to = "biting_status")

## nombre de sites avec présence de piqure par mission, tous villages 
plot_presence_bymission <- ggplot(df_plot_presence, aes(x = as.factor(nummission), fill = biting_status)) + 
    geom_histogram(stat="count") +
    labs(fill = "Biting status", y ="number of sites sampled", x = "mission") +
    theme(legend.position = "bottom") + 
  facet_grid(.~species) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by mission (all villages combined)")

## nombre de sites avec présence de piqure par village, toutes missions 
plot_presence_byvillage <- ggplot(df_plot_presence, aes(x = as.factor(codevillage), fill = biting_status)) + 
    geom_histogram(stat="count") +
    labs(fill = "Biting status", y ="number of sites sampled", x = "mission") +
    theme(legend.position = "bottom",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + 
  facet_grid(.~species) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village (all missions combined)")


## nombre de sites avec présence de piqure par mission, par espèce et par village
plot_presence_byvillagemission_funestus <-  ggplot(df_plot_presence %>% filter(species=="An.funestus_ss"), aes(x = as.factor(nummission), fill = biting_status)) + 
    geom_histogram(stat="count") +
    labs(fill = "Biting status", y ="number of sites sampled", x = "mission") +
    theme(legend.position = "bottom") + 
    facet_wrap(.~codevillage) + 
    #facet_geo(~ codevillage, grid = grid_bf) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.funestus_ss")

plot_presence_byvillagemission_coluzzi <-  ggplot(df_plot_presence %>% filter(species=="An.coluzzii"), aes(x = as.factor(nummission), fill = biting_status)) + 
    geom_histogram(stat="count") +
    labs(fill = "Biting status", y ="number of sites sampled", x = "mission") +
    theme(legend.position = "bottom") + 
    facet_wrap(.~codevillage) + 
    #facet_geo(~ codevillage, grid = grid_bf) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.coluzzii")

plot_presence_byvillagemission_gambiae <-  ggplot(df_plot_presence %>% filter(species=="An.gambiae_ss"), aes(x = as.factor(nummission), fill = biting_status)) + 
    geom_histogram(stat="count") +
    labs(fill = "Biting status", y ="number of sites sampled", x = "mission") +
    theme(legend.position = "bottom") + 
    facet_wrap(.~codevillage) + 
    #facet_geo(~ codevillage, grid = grid_bf) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.gambiae_ss")

(plot_presence_bymission + plot_presence_byvillage) / (plot_presence_byvillagemission_coluzzi + plot_presence_byvillagemission_funestus + plot_presence_byvillagemission_gambiae) + plot_annotation(title = 'Aggressiveness p.1', subtitle = "Indicator : number of sites sampled with presence / absence of bites")

```


## Abundance of bites

```{r }

df <-  dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter((!!sym(col_filter)) %in% species) %>%
  filter(nummission<10, codepays == code_pays) %>%
  group_by(idpostedecapture, (!!sym(col_filter)), codevillage, nummission) %>%
  summarise(n=n())

df2 <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter((!!sym(col_filter)) %in% species) %>%
  filter(nummission<10, codepays == code_pays)


plot_abundance_byvillage_allspecies_percent <- ggplot(df2, aes(x = as.factor(codevillage), fill = (!!sym(col_filter)))) + 
  geom_bar(position="fill") +
  scale_y_continuous(labels = scales::percent) + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
  ggtitle("by village (all missions combined)") +
  labs(x = "village") +
    labs(y = NULL) 

plot_abundance_bymission_allspecies_percent <- ggplot(df2, aes(x = as.factor(nummission), fill = (!!sym(col_filter)))) + 
  geom_bar(position="fill") +
  scale_y_continuous(labels = scales::percent)  + 
  theme(legend.position = "none") +
  ggtitle("by mission (all villages combined)") +
  labs(x = "mission") + 
  labs(y = "number of bites")

plot_abundance_byvillagemission_allspecies_percent <- ggplot(df2, aes(x = as.factor(nummission), fill = (!!sym(col_filter)))) + 
  geom_bar(position="fill") +
  scale_y_continuous(labels = scales::percent) +    
  facet_wrap(.~codevillage) + 
  labs(x = "mission") +
  labs(y = NULL) +
  ggtitle("by village and mission")



stat_box_data <- function(y, upper_limit = max(df$n) * 1.15) {
  return( 
    data.frame(
      y = 0.95 * upper_limit,
      label = paste('n =', length(y), '\n')
    )
  )
}


# all species together
plot_abundance_byvillage_allspecies <- ggplot(df, aes(x = as.factor(codevillage), y = n,  fill = (!!sym(col_filter)))) + 
  geom_bar(stat="identity") + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
  ggtitle("by village (all missions combined)") +
  labs(x = "village") +
    labs(y = NULL) 

plot_abundance_bymission_allspecies <- ggplot(df, aes(x = as.factor(nummission), y = n,  fill = (!!sym(col_filter)))) + 
  geom_bar(stat="identity")  + 
  theme(legend.position = "none") +
  ggtitle("by mission (all villages combined)") +
  labs(x = "mission") + 
  labs(y = "number of bites")

plot_abundance_byvillagemission_allspecies <- ggplot(df, aes(x = as.factor(nummission), y = n,  fill = (!!sym(col_filter)))) + 
  geom_bar(stat="identity") + 
    facet_wrap(.~codevillage) + 
  labs(x = "mission") +
  labs(y = NULL) +
  ggtitle("by village and mission") + 
  theme_bw() #+ scale_fill_manual(values = cbp1)


# cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
#           "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
#theme_bw() + scale_fill_manual(values = cbp1)

# by species
## nombre de piqures par mission et par espèce (comptes positifs) 
plot_abundance_bymission <- ggplot(df, aes(x = as.factor(nummission), y = n)) + 
    geom_boxplot(outlier.shape=NA) +
    geom_jitter(position=position_jitter(0.1), cex=0.4) + 
    stat_summary(fun.data = stat_box_data, geom = "text", hjust = 0.5,vjust = 0.9,size = 2.5) +
  facet_wrap(as.formula(paste(".~", col_filter))) +
  #facet_wrap(.~pcr_espece) +
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by mission (all villages combined)")


## nombre de piqures par village et par espèce (comptes positifs) 
plot_abundance_byvillage <- ggplot(df, aes(x = as.factor(codevillage), y = n)) + 
    geom_boxplot(outlier.shape=NA) +
    geom_jitter(position=position_jitter(0.1), cex=0.4) + 
  facet_wrap(as.formula(paste(".~", col_filter))) +
      theme(legend.position = "bottom",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village (all missions combined)")


df2 <- df %>%
    right_join(df_plot_presence %>% rename(pcr_espece = species)) %>%
  mutate(n = ifelse(is.na(n),0,n)) %>%
  group_by(pcr_espece,codevillage,nummission) %>%
  summarise(n_tot=sum(n)) %>%
  filter(n_tot == 0)

df <- df %>%
  full_join(df2) %>%
  mutate(n = ifelse(is.na(n),0,n))

## nombre de piqures par mission, par village et par espèce (comptes positifs) 
plot_abundance_byvillagemission_funestus <- ggplot(df %>% filter((!!sym(col_filter))=="An.funestus_ss"), aes(x = as.factor(nummission), y = n)) + 
    geom_boxplot(outlier.shape=NA) +
    ylim(1,NA) +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.funestus_ss")

plot_abundance_byvillagemission_coluzzi <- ggplot(df %>% filter((!!sym(col_filter))=="An.coluzzii"), aes(x = as.factor(nummission), y = n)) + 
    geom_boxplot(outlier.shape=NA) +
    ylim(1,NA) +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.coluzzii")

plot_abundance_byvillagemission_gambiae <- ggplot(df %>% filter((!!sym(col_filter))=="An.gambiae_ss"), aes(x = as.factor(nummission), y = n)) + 
    geom_boxplot(outlier.shape=NA) +
    ylim(1,NA) +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.gambiae_ss")


(plot_abundance_bymission + plot_abundance_byvillage) / (plot_abundance_byvillagemission_coluzzi +plot_abundance_byvillagemission_funestus +  plot_abundance_byvillagemission_gambiae) + plot_annotation(title = 'Aggressiveness p.2', subtitle = "Indicator : number of bites / night (positive counts only)")

# barplot version
plot_abundance_bymission_allspecies + plot_abundance_byvillage_allspecies + plot_abundance_byvillagemission_allspecies + plot_annotation(title = 'Aggressiveness p.2', subtitle = "Indicator : number of bites / species / night (positive counts only)")

# barplot version percent
plot_abundance_bymission_allspecies_percent + plot_abundance_byvillage_allspecies_percent + plot_abundance_byvillagemission_allspecies_percent + plot_annotation(title = 'Aggressiveness p.2', subtitle = "Indicator : number of bites / species / night (positive counts only)")

# plot_abundance_byvillage_allspecies <- ggplot(df, aes(x = as.factor(nummission), y = n, fill = pcr_espece)) + 
#     geom_boxplot(outlier.shape=NA) +
#   facet_wrap(.~codevillage)


```


## Behavioral resistance : Exophagy

```{r }

exo <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission <10) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(nummission, codepays, postedecapture,(!!sym(col_filter))) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = postedecapture, values_from = n, values_fill = 0) %>%
  mutate(tot = e+i) %>%
  mutate(exophagy = e / tot * 100)


## proportion des piqures en exterieur par mission et par espèce
plot_exophagy_bymission <- ggplot(exo, aes(x=as.factor(nummission), y = exophagy, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ylab("frequency of bites") +
    labs(x = NULL) +
    labs(y = NULL) +
  geom_hline(yintercept=50, linetype="dashed", color = "red") +
  ggtitle("% bites outdoor by mission (all villages combined)")

## proportion des piqures en exterieur par village et par espèce
exo2 <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission <10) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(codepays, codevillage, postedecapture,(!!sym(col_filter))) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = postedecapture, values_from = n) %>%
  mutate(tot = e+i) %>%
  mutate(exophagy = e / tot * 100)

plot_exophagy_byvillage <- ggplot(exo2, aes(x=as.factor(codevillage), y = exophagy, label = tot)) + 
  geom_bar(stat="identity") + 
   #geom_text(vjust = 2, size = 2, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ylab("frequency of bites") + 
    labs(x = NULL) +
    labs(y = NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    geom_hline(yintercept=50, linetype="dashed", color = "red") +
  ggtitle("% bites outdoor by village (all missions combined)")


exo_byvillage <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays,nummission<10) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(nummission, codepays, codevillage, postedecapture,(!!sym(col_filter))) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = postedecapture, values_from = n) %>%
  mutate_all(funs(replace_na(., 0))) %>%
  mutate(tot = e+i) %>%
  mutate(exophagy = e / tot * 100) %>%
  #full_join(df2) %>%
  mutate(exophagy = ifelse(is.na(exophagy),0,exophagy))

## proportion des piqures en exterieur par mission, par espèce et par village
plot_exophagy_byvillagemission_funestus <- ggplot(exo_byvillage %>% filter((!!sym(col_filter))=="An.funestus_ss"), aes(x=as.factor(nummission), y = exophagy)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.funestus_ss")

plot_exophagy_byvillagemission_coluzzi <-  ggplot(exo_byvillage %>% filter((!!sym(col_filter))=="An.coluzzii"), aes(x=as.factor(nummission), y = exophagy)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.coluzzii")
  
plot_exophagy_byvillagemission_gambiae <-  ggplot(exo_byvillage %>% filter((!!sym(col_filter))=="An.gambiae_ss"), aes(x=as.factor(nummission), y = exophagy)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.gambiae_ss")

(plot_exophagy_bymission + plot_exophagy_byvillage) / ( plot_exophagy_byvillagemission_coluzzi + plot_exophagy_byvillagemission_funestus +plot_exophagy_byvillagemission_gambiae) + plot_annotation(title = "Behavioral resistance / exophagy",  subtitle = "Indicator : proportion of bites occurring outside")

```


## Bahavioral resistance : number of bites by hour, early and late biting

```{r }

entomo_csh_metadata_l1 <- dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% dplyr::select(-geom) %>% filter(!(nummission %in% c("11","12","13","15")))

th_trmetrics_entomo_postedecapture <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>% 
              dplyr::select(-fid) %>% 
              left_join(entomo_csh_metadata_l1 %>% dplyr::select(idpointdecapture, period_interv)) %>% 
              filter(codepays == code_pays, nummission <= 8)

  
source("r_scripts/data_analysis_tests/functions_script_data_analysis.R")

HB_data <- load_hmnbehav_data(code_pays,entomo_csh_metadata_l1)$hum_behav_4_exophagy

ELB <- th_trmetrics_entomo_postedecapture %>%
             left_join(HB_data) %>%
             mutate(ELB = case_when(HBB > 50 ~ "nocturnal",
                                    HBB < 50 & heuredecapture > 15 ~ "early_biting",
                                    HBB < 50 & heuredecapture < 10 ~ "late_biting")) %>%
             mutate(ELB = forcats::fct_relevel(ELB,c("nocturnal","early_biting","late_biting")))
          
df_ELB_bymission <- ELB %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(nummission, ELB,(!!sym(col_filter))) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = ELB, values_from = n, values_fill = 0) %>%
  mutate(tot = nocturnal+early_biting+late_biting) %>%
  mutate(perc_early_biting = early_biting / tot * 100, perc_late_biting = late_biting / tot * 100, perc_earlylatebiting = (early_biting + late_biting)/tot * 100)


plot_earlybiting_bymission <- ggplot(df_ELB_bymission, aes(x=as.factor(nummission), y = perc_early_biting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% early bites (before 50% of pop. is indoor) (all villages combined)")

plot_latebiting_bymission <- ggplot(df_ELB_bymission, aes(x=as.factor(nummission), y = perc_late_biting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% late bites (after 50% of pop. is outdoor) (all villages combined)")

plot_earlylatebiting_bymission <- ggplot(df_ELB_bymission, aes(x=as.factor(nummission), y = perc_earlylatebiting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% early or late bites (before / after 50% of pop. is indoor/outdoor) (all villages combined)")


df_ELB_byvillage <- ELB %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(codevillage, ELB,(!!sym(col_filter))) %>%
  summarise(n=n()) %>%
  pivot_wider(names_from = ELB, values_from = n, values_fill = 0) %>%
  mutate(tot = nocturnal+early_biting+late_biting) %>%
  mutate(perc_early_biting = early_biting / tot * 100, perc_late_biting = late_biting / tot * 100, perc_earlylatebiting = (early_biting + late_biting)/tot * 100)


plot_earlybiting_byvillage <- ggplot(df_ELB_byvillage, aes(x=as.factor(codevillage), y = perc_early_biting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% early bites (before 50% of pop. is intdoor) (all missions combined)")

plot_latebiting_byvillage <- ggplot(df_ELB_byvillage, aes(x=as.factor(codevillage), y = perc_late_biting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% late bites (after 50% of pop. is outdoor) (all missions combined)")

plot_earlylatebiting_byvillage <- ggplot(df_ELB_byvillage, aes(x=as.factor(codevillage), y = perc_earlylatebiting, label = tot)) + 
  geom_bar(stat="identity") +  
  geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  facet_grid(as.formula(paste(".~", col_filter))) +
  ylim(0, 100) + 
  ggtitle("% early or late bites (before / after 50% of pop. is indoor/outdoor) (all missions combined)")


plot_earlybiting_bymission + plot_earlybiting_byvillage
plot_latebiting_bymission + plot_latebiting_byvillage
plot_earlylatebiting_bymission + plot_earlylatebiting_byvillage

```







```{r }

bites <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission < 10) %>%
  left_join(villages_missions_interv) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by( (!!sym(col_filter)),nummission) %>%
  summarise(n_tot=n())

## nombre moyen de piqures par heure / par mission  (linegraph) TODO
bites_by_hour <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission < 10) %>%
  left_join(villages_missions_interv) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  group_by(heuredecapture,(!!sym(col_filter)),postedecapture, nummission) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  left_join(bites) %>%
  mutate(perc = n/n_tot * 100) %>%
  #group_by(intervention, heuredecapture,pcr_espece, period_interv) %>%
  #summarise(n = n(),vale=mean(perc), upper = max(perc), lower =  min(perc)) %>%
  #as_tibble() %>%
  mutate(heuredecapture = forcats::fct_relevel(as.character(heuredecapture),c("17","18","19","20","21","22","23","0","1","2","3","4","5","6","7","8"))) %>%
  filter(n_tot > 56 ) %>% 
  tidyr::complete(heuredecapture,(!!sym(col_filter)),postedecapture, nummission)#%>%
  #mutate(period_interv = forcats::fct_relevel(period_interv,c("pre_intervention","post_intervention")))



plot_bites_by_hour <- ggplot(bites_by_hour, aes(x=heuredecapture, y = perc, group = postedecapture, colour = as.factor(postedecapture))) + 
    geom_line() + 
    #geom_ribbon(aes(ymin=lower, ymax=upper), linetype=2, alpha=0.7, fill = "grey70") +
    facet_wrap(as.formula(paste(col_filter,"~nummission")), nrow = 3, ncol = 7, scales  = "free_y") +
    theme_bw()



## heure médiane de piqure par mission (boxplot) TODO
bites_by_hour <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission < 10) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  left_join(periodes_interv %>% dplyr::select(idpointdecapture, date_capture)) %>%
  mutate(date_capture = lubridate::ymd(date_capture))


  t = dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% 
    filter(!(nummission %in% c("11","12","13","15"))) %>%
      filter(codepays == code_pays) %>%
      mutate(periode = ifelse(period_interv=="pre_intervention","preinterv","postinterv")) %>%
      mutate(date_capture = as.Date(date_capture)) %>%
      mutate(month = lubridate::month(date_capture)) %>%
      mutate(saison = ifelse(month <= 4 | month >=11 , "seche","pluies")) %>%
      dplyr::select(idpointdecapture,codevillage,periode,saison)
    
  HBB <- dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>% 
      filter(codepays == code_pays) %>%
      mutate(hcoucher = as.numeric(substr(hcoucher,1,2)),hlever=as.numeric(substr(hlever,1,2))) %>%
      mutate(hcoucher = ifelse(hcoucher <=17, 20, hcoucher), hlever=ifelse(hlever>=11 | hlever<=3,6,hlever)) %>%
      group_by(codevillage,periode,saison) %>%
      summarise(hcoucher=round(mean(hcoucher)),hlever=round(mean(hlever)))
    
  
  late_prec_agg_byvillagemission <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
    filter(codepays == "BF") %>%
    filter(pcr_espece %in% c("An.funestus_ss", "An.coluzzii", "An.gambiae_ss"), nummission <10) %>%
    left_join(t) %>%
    left_join(HBB) %>%
    mutate(late_prec_aggre = ifelse(heuredecapture >= hlever & heuredecapture <= hcoucher,"early_or_late","normal")) %>%
    group_by(codevillage, nummission, pcr_espece, late_prec_aggre) %>%
    summarise(n=n()) %>%
    as_tibble() %>%
    pivot_wider(names_from = late_prec_aggre, values_from = n, values_fill = list(n = 0) ) %>%
    mutate(perc_early_or_late =  early_or_late / (early_or_late + normal) * 100)

## proportion des piqures avant 20h le soir et après 6h le matin par mission (barplot)
late_prec_agg_byvillagemission <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == code_pays, nummission < 10) %>%
  filter((!!sym(col_filter)) %in% species) %>%
  mutate(late_prec_aggre = ifelse(as.numeric(heuredecapture) >= 6 & as.numeric(heuredecapture) <= 20,"early_or_late","normal")) %>%
  group_by(codevillage, nummission, (!!sym(col_filter)), late_prec_aggre) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  pivot_wider(names_from = late_prec_aggre, values_from = n, values_fill = list(n = 0) ) %>%
  mutate(perc_early_or_late =  early_or_late / (early_or_late + normal) * 100)

late_prec_agg_bymission <- late_prec_agg_byvillagemission %>%
  group_by(nummission, (!!sym(col_filter))) %>%
  summarise(normal = sum(normal), early_or_late = sum(early_or_late)) %>%
  mutate(tot = early_or_late + normal) %>%
  mutate(perc_early_or_late =  early_or_late / tot * 100)

late_prec_agg_byvillage <- late_prec_agg_byvillagemission %>%
  group_by(codevillage, (!!sym(col_filter))) %>%
  summarise(normal = sum(normal), early_or_late = sum(early_or_late)) %>%
  mutate(tot = early_or_late + normal) %>%
  mutate(perc_early_or_late =  early_or_late / tot * 100)

# par village, toutes missions
plot_lateprecagg_byvillage <- ggplot(late_prec_agg_byvillage, aes(x=as.factor(codevillage), y = perc_early_or_late)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(as.formula(paste(".~", col_filter))) +
  ggtitle("by village (all missions combined)") + 
    labs(x = NULL) +
    labs(y = NULL) +
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


# par mission, tous villages
plot_lateprecagg_bymission <- ggplot(late_prec_agg_bymission, aes(x=as.factor(nummission), y = perc_early_or_late, label = tot)) + 
  geom_bar(stat="identity") + 
  geom_text(vjust = 2, size = 3,position = position_dodge(width = 1)) +
  ylab("frequency of bites") +
  facet_wrap(as.formula(paste(".~", col_filter))) +
  ggtitle("by mission (all villages combined)") + 
    labs(x = NULL) +
    labs(y = NULL) +
  ylim(0,100)

# par village et par mission
plot_lateprecagg_byvillagemission_funestus <- ggplot(late_prec_agg_byvillagemission %>% filter((!!sym(col_filter))=="An.funestus_ss"), aes(x=as.factor(nummission), y = perc_early_or_late)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.funestus_ss")

plot_lateprecagg_byvillagemission_coluzzi <- ggplot(late_prec_agg_byvillagemission %>% filter( (!!sym(col_filter))=="An.coluzzii"), aes(x=as.factor(nummission), y = perc_early_or_late)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.coluzzii")

plot_lateprecagg_byvillagemission_gambiae <- ggplot(late_prec_agg_byvillagemission %>% filter( (!!sym(col_filter))=="An.gambiae_ss"), aes(x=as.factor(nummission), y = perc_early_or_late)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
  ggtitle("by village and mission, An.gambiae_ss")

(plot_lateprecagg_bymission + plot_lateprecagg_byvillage) /  ( plot_lateprecagg_byvillagemission_coluzzi + plot_lateprecagg_byvillagemission_funestus + plot_lateprecagg_byvillagemission_gambiae) + plot_annotation(title = "Behavioral resistance / early or late biting", subtitle = 'Indicator : proportion of bites occurring before 8 p.m. or after 6 a.m.')
```


## Physiological resistance : frequencies of kdr allel 

```{r }
## frequence allelique de chaque gène de résistance
kdrw_bymission_allvillages <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == "BF") %>%
  filter(pcr_espece %in% c("An.coluzzii", "An.gambiae_ss"), nummission <10) %>%
  group_by(nummission, pcr_espece, kdrw) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  filter(!is.na(kdrw)) %>%
  pivot_wider(names_from = kdrw, values_from = n, values_fill = list(n = 0) ) %>%
  mutate(tot = RR+RS+SS) %>%
  mutate(freq_allel = 100* (2*RR + RS) / (2*(RR+RS+SS)))

kdrw_byvillage_allmissions <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == "BF") %>%
  filter(pcr_espece %in% c("An.coluzzii", "An.gambiae_ss"), nummission <10) %>%
  group_by(codevillage, pcr_espece, kdrw) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  filter(!is.na(kdrw)) %>%
  pivot_wider(names_from = kdrw, values_from = n, values_fill = list(n = 0) ) %>%
  mutate(freq_allel = 100* (2*RR + RS) / (2*(RR+RS+SS)))


kdrw_byvillage <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>%
  filter(codepays == "BF") %>%
  filter(pcr_espece %in% c("An.coluzzii", "An.gambiae_ss"), nummission <10) %>%
  group_by(codevillage, nummission, pcr_espece, kdrw) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  filter(!is.na(kdrw)) %>%
  pivot_wider(names_from = kdrw, values_from = n, values_fill = list(n = 0) ) %>%
  mutate(freq_allel = 100* (2*RR + RS) / (2*(RR+RS+SS)))

# par village, toutes missions
plot_kdrw_byvillage <- ggplot(kdrw_byvillage_allmissions, aes(x=as.factor(codevillage), y = freq_allel)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~pcr_espece) +
  ggtitle("by village (all missions combined)") +
    labs(x = NULL) +
    labs(y = NULL) +
  ylim(0,100) + 
    geom_hline(yintercept=50, linetype="dashed", color = "red") +
  theme(legend.position = "bottom",axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  +
  ggtitle("Allelic freq. kdre by village (all missions combined)")


# par mission, tous villages
plot_kdrw_bymission <- ggplot(kdrw_bymission_allvillages, aes(x=as.factor(nummission), y = freq_allel, label = tot)) + 
  geom_bar(stat="identity") + 
    geom_text(vjust = 2, size = 3, position = position_dodge(width = 1)) +
  ylab("frequency of bites") +
  facet_wrap(.~pcr_espece) +
    labs(x = NULL) +
    labs(y = NULL) +
    ylim(0,100) + 
    geom_hline(yintercept=50, linetype="dashed", color = "red") +
  ggtitle("Allelic freq. kdre by mission (all villages combined)")

# par village et par mission
plot_kdrw_byvillagemission_coluzzi <- ggplot(kdrw_byvillage %>% filter(pcr_espece=="An.coluzzii"), aes(x=as.factor(nummission), y = freq_allel)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
    ylim(0,100) + 
  ggtitle("by village and mission, An.coluzzii")

plot_kdrw_byvillagemission_gambiae <- ggplot(kdrw_byvillage %>% filter(pcr_espece=="An.gambiae_ss"), aes(x=as.factor(nummission), y = freq_allel)) + 
  geom_bar(stat="identity") + 
  ylab("frequency of bites") +
  facet_wrap(.~codevillage) + 
    labs(x = NULL) +
    labs(y = NULL) +
    ylim(0,100) + 
  ggtitle("by village and mission, An.gambiae_ss")

(plot_kdrw_bymission + plot_kdrw_byvillage) / (plot_kdrw_byvillagemission_coluzzi + plot_kdrw_byvillagemission_gambiae) + plot_annotation(title = "Physiological resistance", subtitle = 'Indicator : allelic frequency of the kdrw mutation')

```


## LAV


## LLIN use and human pop. behaviour
```{r }
lct <- Sys.getlocale("LC_TIME"); Sys.setlocale("LC_TIME", "C")
mean_dates_lus = dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>%
  dplyr::select(-geom) %>%
  group_by(codepays,survey) %>%
  summarise(date = mean(as.Date(dateenquete))) %>%
  mutate(mois = lubridate::month(date,label=T)) %>%
  mutate(annee = lubridate::year(date)) %>%
  mutate(date = paste0(annee," - ",mois))


lus_byvillage = dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>%
  dplyr::select(-geom) %>%
  group_by(codevillage,codepays,survey,dormirssmoust) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  pivot_wider(names_from = dormirssmoust, values_from = n, values_fill = list(n = 0)) %>%
  mutate(perc_users_llin = oui / (non + oui) * 100) %>%
  pivot_longer(c("non","oui")) %>%
  filter(name == "oui") %>%
  group_by(survey,codepays) %>%
  summarise(sd_perc_users_llin=sd(perc_users_llin))

lus_bymission = dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>%
  dplyr::select(-geom) %>%
  group_by(codepays,survey,dormirssmoust) %>%
  summarise(n=n()) %>%
  as_tibble() %>%
  pivot_wider(names_from = dormirssmoust, values_from = n, values_fill = list(n = 0)) %>%
  mutate(perc_users_llin = oui / (non + oui) * 100) %>%
  pivot_longer(c("non","oui"))  %>%
  filter(name == "oui")


lus <- left_join(lus_byvillage,lus_bymission) %>% 
  left_join(mean_dates_lus) %>%
  mutate(survey = case_when(codepays=="CI" & survey == 2 ~ 1,
                            codepays=="CI" & survey == 3 ~ 2,
                            codepays=="BF" ~ survey)) %>%
    mutate(survey = as.factor(survey)) %>%
  mutate(codepays = ifelse(codepays=="CI","Korhogo (IC)","Diébougou (BF)")) %>%
  mutate(codepays = forcats::fct_relevel(codepays,"Korhogo (IC)","Diébougou (BF)")) %>%
  mutate(lower = perc_users_llin - sd_perc_users_llin, upper = perc_users_llin + sd_perc_users_llin) %>%
  mutate(upper = ifelse(upper>100,100,upper))

plot_lus <- ggplot(lus , aes(x=survey, y = perc_users_llin, fill = name)) +
  geom_col(fill = "grey") + 
   ylim(c(0,100)) +
   geom_errorbar(aes(ymin = lower, ymax = upper), position = position_dodge(0.9), width = 0.25) +
   facet_grid(.~codepays, scales = "free_x") + 
   theme(legend.position = "none") + 
   ylab("% of users of LLIN")+ 
   xlab("Human behaviour survey") + 
   theme_bw() + 
   labs(title = "Human behaviour", subtitle = "% of population that use LLIN for each study area and human behaviour survey", 
        caption = "Values were averaged over all the villages. \nError bars indicate the mean +- sd for all the study villages for the considered survey")

ggsave(filename="humbehav_lus.png",plot=plot_lus,path="/home/ptaconet/phd/articles/article2",dpi = 300)

####### early / late biting



HBI <- dbReadTable(react_gpkg, 'entomo_comportementhumain_l0') %>% 
    dplyr::select(-geom) %>%
  filter(dormirssmoust=="oui") %>%
     mutate(hintmaison_h = as.numeric(substr(hintmaison,1,2)),hsortiemaison_h=as.numeric(substr(hsortiemaison,1,2))) %>%
     mutate(hintmaison_h = ifelse(hintmaison_h <=16, 19, hintmaison_h), hsortiemaison_h=ifelse(hsortiemaison_h>=11 | hsortiemaison_h<=3,6,hsortiemaison_h)) %>%
   mutate(hcoucher_h = as.numeric(substr(hcoucher,1,2)),hlever_h=as.numeric(substr(hlever,1,2))) %>%
   mutate(hcoucher_h = ifelse(hcoucher_h <=17, 20, hcoucher_h), hlever_h=ifelse(hlever_h>=11 | hlever_h<=3,6,hlever_h)) %>%
  mutate(hintmaison_m = as.numeric(substr(hintmaison,4,5)),hsortiemaison_m=as.numeric(substr(hsortiemaison,4,5)),hlever_m = as.numeric(substr(hlever,4,5)),hcoucher_m=as.numeric(substr(hcoucher,4,5))) %>%
    mutate(hintmaison_m = case_when(hintmaison_m >=0 & hintmaison_m <30 ~ 0,
                                    hintmaison_m > 30 ~ 0.75,
                                    hintmaison_m == 30 ~ 0.5)) %>%
      mutate(hsortiemaison_m = case_when(hsortiemaison_m >=0 & hsortiemaison_m <30 ~ 0,
                                    hsortiemaison_m > 30 ~ 0.75,
                                    hsortiemaison_m == 30 ~ 0.5)) %>%
      mutate(hlever_m = case_when(hlever_m >=0 & hlever_m <30 ~ 0,
                                    hlever_m > 30 ~ 0.75,
                                    hlever_m == 30 ~ 0.5)) %>%
      mutate(hcoucher_m = case_when(hcoucher_m >=0 & hcoucher_m <30 ~ 0,
                                    hcoucher_m > 30 ~ 0.75,
                                    hcoucher_m == 30 ~ 0.5)) %>%
 mutate(hintmaison = hintmaison_h + hintmaison_m, hcoucher = hcoucher_h + hcoucher_m, hlever = hlever_h +hlever_m, hsortiemaison = hsortiemaison_h + hsortiemaison_m) %>%
  mutate(survey = case_when(codepays=="CI" & survey == 2 ~ 1,
                            codepays=="CI" & survey == 3 ~ 2,
                            codepays=="BF" ~ survey)) %>%
    mutate(survey = as.factor(survey)) %>%
  mutate(codepays = ifelse(codepays=="CI","Korhogo (IC)","Diébougou (BF)")) %>%
  mutate(codepays = forcats::fct_relevel(codepays,"Korhogo (IC)","Diébougou (BF)"))


HBI_hmedian <- HBI %>%
  group_by(codepays,survey) %>%
  summarize(med_hintmaison = median(hintmaison),
            med_hsortiemaison = median(hsortiemaison),
            med_hcoucher = median(hcoucher),
            med_hlever = median(hlever))


p_hintmaison <- ggplot(data = HBI) +
  stat_ecdf(aes(hintmaison), geom = "line") + 
  geom_vline(data = HBI_hmedian, aes(xintercept = med_hintmaison), linetype = "dashed", color = "red") + 
  geom_label(data = HBI_hmedian, mapping = aes(x = med_hintmaison, y = 0.1, label = med_hintmaison), color = "red" ) + 
  facet_wrap(codepays~survey, ncol = 5, nrow = 1) + 
  ggtitle("indoor (night)") + 
  theme_bw() + 
  ylab("Pop. freq.") + 
  xlab("time (hour)")

p_hsortiemaison <- ggplot(data = HBI) +
  stat_ecdf(aes(hsortiemaison), geom = "line") + 
  geom_vline(data = HBI_hmedian, aes(xintercept = med_hsortiemaison), linetype = "dashed", color = "red") + 
  geom_label(data = HBI_hmedian, mapping = aes(x = med_hsortiemaison, y = 0.1, label = med_hsortiemaison), color = "red" ) + 
  facet_wrap(codepays~survey, ncol = 5, nrow = 1) + 
  ggtitle("outdoor (morning)") + 
  theme_bw() + 
  ylab("Pop. freq.") + 
  xlab("time (hour)")

p_hcoucher <- ggplot(data = HBI) +
  stat_ecdf(aes(hcoucher), geom = "step") + 
  geom_vline(data = HBI_hmedian, aes(xintercept = med_hcoucher), linetype = "dashed", color = "red") + 
  geom_label(data = HBI_hmedian, mapping = aes(x = med_hcoucher, y = 0.1, label = med_hcoucher), color = "red" ) + 
  facet_wrap(codepays~survey, ncol = 5, nrow = 1) + 
  ggtitle("under LLIN (night)") + 
  theme_bw() + 
  ylab("Pop. freq.") + 
  xlab("time (hour)")

p_hlever <- ggplot(data = HBI) +
  stat_ecdf(aes(hlever), geom = "step") + 
  geom_vline(data = HBI_hmedian, aes(xintercept = med_hlever), linetype = "dashed", color = "red") + 
  geom_label(data = HBI_hmedian, mapping = aes(x = med_hlever, y = 0.1, label = med_hlever), color = "red" ) + 
  facet_wrap(codepays~survey, ncol = 5, nrow = 1) + 
  ggtitle("out of LLIN (morning)") + 
  theme_bw() + 
  ylab("Pop. freq.") + 
  xlab("time (hour)")


p <- wrap_plots(list(p_hintmaison,p_hsortiemaison,p_hcoucher,p_hlever), nrow = 2, ncol = 2) + plot_annotation(title = 'Human behaviour',
                                                                                                         subtitle = "% of population indoor, outdoor, under an LLIN and out of LLIN for each study area and human behaviour survey",
                                                                                                         caption = "The red line indicates the median time.")
# ggplot(data = HBI) +
#   geom_line(aes(x = hintmaison, colour = as.factor(survey)), stat='ecdf') +
#   facet_wrap(.~codepays)

  ggsave(filename="humbehav_hbi.png",plot=p,path="/home/ptaconet/phd/articles/article2",dpi = 300)

source("r_scripts/data_analysis_tests/functions_script_data_analysis.R")

entomo_csh_metadata_l1 <- dbReadTable(react_gpkg, 'entomo_csh_metadata_l1') %>% dplyr::select(-geom) %>% filter(!(nummission %in% c("11","12","13","15")))

## BF
th_trmetrics_entomo_postedecapture <- dbReadTable(react_gpkg, 'entomo_idmoustiques_l0') %>% 
  dplyr::select(-fid) %>% 
  left_join(entomo_csh_metadata_l1 %>% dplyr::select(idpointdecapture, period_interv)) %>% 
  filter(codepays == "BF", nummission <= 8)

HB_data <- load_hmnbehav_data("BF",entomo_csh_metadata_l1)$hum_behav_4_exophagy
HB_data <- HB_data %>%
  mutate(nummission = substr(idpointdecapture,0,1), codevillage = substr(idpointdecapture,2,4)) %>%
  dplyr::select(-idpointdecapture) %>%
  distinct() %>%
  
  mutate(heuredecapture = as.factor(heuredecapture)) %>%
  mutate(heuredecapture=forcats::fct_relevel(heuredecapture,c("16", "17", "18", "19" ,"20", "21", "22", "23", "0", "1" ,"2", "3", "4", "5", "6", "7", "8", "9", "10")))

```



## Climate variables
```{r }

vars = c("RFD1F","TMAX1","TMIN1")

env_spatiotemporal <- dbReadTable(react_gpkg, 'env_spatiotemporal') %>% 
  dplyr::select(-fid) %>% 
  mutate(date = as.Date(date)) %>% 
  dplyr::rename(idpointdecapture = id) %>% 
  filter(var %in% vars, buffer == 2000) %>%
  mutate( week = sprintf("%02d", lubridate::week(date)), year = lubridate::year(date), month = lubridate::month(date)) %>%
  mutate( week = ifelse(week == 53,52,week)) %>%
  left_join(periodes_interv) %>%
  filter( as.numeric(nummission)<10) %>%
  mutate(date = as.Date(paste0(year,week,"1"),"%Y%U%u"))

rfd <- env_spatiotemporal %>%
  filter(var == "RFD1F", !is.na(date)) %>%
  group_by(var, codepays,codevillage, lag_time, nummission, date) %>%
  summarise(val = mean(val,na.rm = TRUE)) %>%
  as_tibble() %>%
  group_by(codepays,codevillage, date, var) %>%
  summarise(val=sum(val))

oth <- env_spatiotemporal %>%
  filter(var != "RFD1F") %>%
  group_by(var,codepays, codevillage, date) %>%
  summarise(val=mean(val, na.rm = T))

env_spatiotemporal <- rbind(rfd,oth) %>%
  group_by(codepays,date,var) %>%
  summarise(vale=mean(val), upper = mean(val) - sd(val), lower = mean(val) + sd(val)) %>%
  as_tibble() %>%
  left_join(prediction_vars %>% dplyr::select(code,short_name,unit), by=c("var"="code")) %>%
  mutate(variable = paste0(short_name," (", unit,")")) %>%
  mutate(variable = gsub("LST", "land surface temperature",variable)) %>%
  mutate(codepays = ifelse(codepays=="CI","Korhogo (IC)","Diébougou (BF)"))
  mutate(codepays = forcats::fct_relevel(codepays,"Korhogo (IC)","Diébougou (BF)"))

# BF only
env_spatiotemporal$vale[which(env_spatiotemporal$date=="2017-07-03" & env_spatiotemporal$codepays=="BF")] <- NaN
env_spatiotemporal$upper[which(env_spatiotemporal$date=="2017-07-03" & env_spatiotemporal$codepays=="BF")] <- NaN
env_spatiotemporal$lower[which(env_spatiotemporal$date=="2017-07-03" & env_spatiotemporal$codepays=="BF")] <- NaN


mean_date_by_mission <- periodes_interv %>%
  mutate(nummission = as.numeric(nummission)) %>%
  filter(nummission < 10) %>%
  mutate(date_capture = as.Date(date_capture)) %>%
  group_by(codepays,nummission) %>%
  summarise(date=mean(date_capture)) %>%
  mutate(codepays = ifelse(codepays=="CI","Korhogo (IC)","Diébougou (BF)"))


plot_climate_byvillagemission <- ggplot(env_spatiotemporal , aes(x=date, y = val, fill = codevillage)) + 
  geom_line(size = 0.2) + 
  geom_ribbon(aes(ymin=data$lower, ymax=data$upper), linetype=2, alpha=0.1) + 
  scale_x_date() +
  facet_wrap(.~var, scales = "free") +
  geom_vline(data = mean_date_by_mission, aes(xintercept = date, color = "red"),linetype=2, size = 0.5)


plot_climate_byvillagemission <- ggplot(env_spatiotemporal) + 
    scale_x_date(aes(x=date, y = vale)) +
    facet_wrap(codepays~variable, scales = "free_y", nrow = 2, ncol = 3) +
    geom_ribbon(aes(x=date, y = vale,ymin=lower, ymax=upper), linetype=2, alpha=0.7, fill = "grey70") +
    geom_line(aes(x=date, y = vale),size = 0.2) + 
    theme_bw() +
    geom_vline(data = mean_date_by_mission, aes(xintercept = date, color = "red"),linetype=2, size = 0.5)  +     
    geom_rect(data = mean_date_by_mission, aes(xmin = date - 30, xmax = date), ymin = -Inf, ymax = Inf, alpha = 0.2, fill = "blue" ) + 
    geom_label(data = mean_date_by_mission, mapping = aes(x=date, y = 0, label = nummission, vjust = -0.3), colour = "red") +
    theme(legend.position= "none") +
    labs(y = NULL, title = "Past weather", subtitle = "Weekly mean (for land surface temperature) and sum (for rainfall) in a 2 km buffer around each collection point.", caption = "Solid bars indicate the mean for all the collection points in the considered week.\nGrey ribbons indicates the mean ± the standard deviation (i.e. spatial variability).\nRed vertical lines indicate the dates of the entomological surveys.\nBlue ribbons indicate a time frame of one month before each entomological survey.\ndata sources : GPM (rainfall), MODIS (temperature)")

ggsave(filename="past_weather.png",plot=plot_climate_byvillagemission,path="/home/ptaconet/phd/articles/article2",dpi = 300)


```


## land cover
```{r }
env_lc <- dbReadTable(react_gpkg, 'env_landcover') %>% 
  left_join(dbReadTable(react_gpkg, 'lco_metadata') %>% dplyr::select(layer_id,pixval,pixlabel_english)) %>%
  rename(idpointdecapture = id) %>%
  left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays)) %>%
  dplyr::select(-fid) %>%
  filter(layer_id == ifelse(code_pays=="BF",3,8), metric == "pland", codepays == code_pays, buffer %in% c(250,500,1000,2000)) %>%
  group_by(codevillage,pixlabel_english,buffer) %>%
  summarise(val=mean(val)) %>%
  as_tibble()

env_lc_permanent_waters <- dbReadTable(react_gpkg, 'env_landcover') %>% 
  left_join(dbReadTable(react_gpkg, 'lco_metadata') %>% dplyr::select(layer_id,pixval,pixlabel_english)) %>%
  rename(idpointdecapture = id) %>%
  left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays)) %>%
  dplyr::select(-fid) %>%
  filter(layer_id == ifelse(code_pays=="BF",2,7), pixval == ifelse(code_pays=="BF",5,6), metric == "pland", codepays == code_pays, buffer %in% c(250,500,1000,2000)) %>%
  group_by(codevillage,pixlabel_english,buffer) %>%
  summarise(val=mean(val)) %>%
  as_tibble()
  
plot_landcover_byvillage <- ggplot(env_lc, aes(x=as.factor(codevillage), y=val, fill = pixlabel)) +
  geom_bar(stat="identity") + 
  ggtitle("Land cover", subtitle = "Mean of each land cover class in a 2000m buffer around the center of the village")

env_lc_permanent_waters <- env_lc_permanent_waters %>%
   group_by(pixlabel_english, buffer) %>%
  summarise(vale = mean(val),sd = sd(val)) %>%
  as_data_frame()

env_lc2 <- env_lc %>%
  group_by(pixlabel_english, buffer) %>%
  summarise(vale = mean(val),sd = sd(val)) %>%
  as_data_frame() %>%
  dplyr::filter(!(pixlabel_english %in% c("Still waters","Running waters"))) %>%
  bind_rows(env_lc_permanent_waters) %>%
  mutate(buffer = as.factor(paste0(buffer, " m buffer"))) %>%
  mutate(buffer = forcats::fct_relevel(buffer,c("250 m buffer","500 m buffer","1000 m buffer","2000 m buffer")))


plot_landcover_byvillage2 <- ggplot(env_lc2, aes(x=reorder(pixlabel_english,-vale), y=vale)) +
    geom_bar(stat="identity") + 
  facet_wrap(.~buffer, ncol = 2, nrow = 2) +
      geom_errorbar(aes(ymin=vale-sd, ymax=vale+sd), width=.15,position=position_dodge(.9)) +
    labs(title = "Land cover", caption = "Data source : land cover map built from a supervised classification using satellite images", subtitle = "Average percentage of surface occupied by each land cover class in various buffer sizes around the catch point.\nError bars indicate the mean +- sd for all the collection points of the study area") + theme_bw() + ylab("% land cover") + xlab("land cover class") + theme(axis.text.x = element_text(angle = 55, hjust=1)) +
  ylab("% landscape") + 
  xlab("")


plot_landcover_byvillage2
```


## other spatial variables
```{r }
oth_spatial <- dbReadTable(react_gpkg, 'env_spatial') %>% 
    rename(idpointdecapture = id) %>%
    left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays)) %>%
  filter(buffer == 2000) %>%
    group_by(codepays,codevillage, var) %>%
  summarise(val=mean(val)) %>%
      left_join(prediction_vars %>% dplyr::select(code,short_name,unit), by=c("var"="code"))

oth_spatial2 <- dbReadTable(react_gpkg, 'env_spatial') %>% 
    rename(idpointdecapture = id) %>%
    left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays)) %>%
  filter(buffer == 500, var %in% c("BCH","POP")) %>%
    group_by(codepays,codevillage, var) %>%
  summarise(val=mean(val)) %>%
      left_join(prediction_vars %>% dplyr::select(code,short_name,unit), by=c("var"="code"))
  
env_static <- dbReadTable(react_gpkg, 'env_static') %>%
    dplyr::rename(idpointdecapture = id) %>% 
    left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays)) %>%
    filter(var %in% c("WMD","BDE")) %>%
    group_by(codepays,codevillage, var) %>%
    summarise(val=mean(as.numeric(val))) %>%
    left_join(prediction_vars %>% dplyr::select(code,short_name,unit), by=c("var"="code")) %>%
  filter(!is.na(codepays))

oth_spatial <- rbind(oth_spatial,oth_spatial2,env_static)
  
plot_othspa_byvillage <- ggplot(oth_spatial, aes(x=as.factor(codevillage), y=val)) +
  geom_bar(stat="identity") +
  facet_wrap(codepays~short_name, scales="free") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=0.5)) + 
  labs(x = NULL) +
  labs(y = NULL) +
  ggtitle("Other spatial variables", subtitle = "Mean in a 2000m buffer around the center of the village")

plot_othspa_byvillage


crops_bf <- dbReadTable(react_gpkg, 'env_landcover') %>% 
  filter(buffer == 2000, layer_id==3, pixval %in% c(1,11), metric=="pland") %>%
  mutate(codevillage = substr(id,2,4)) %>%
  dplyr::group_by(codevillage) %>%
  summarise(val = mean(val)) %>%
  mutate(codepays="BF",var="crop",short_name="Surface of crops", unit="% of landscape in a 2 km buffer area")


oth_spatial2 <- oth_spatial %>%
  bind_rows(crops_bf) %>%
  mutate(short_name = paste0(short_name,"\n(",unit,")")) %>%
  # group_by(codepays,short_name) %>%
  # summarise(vale = mean(val, na.rm = T),sd = sd(val, na.rm = T)) %>% 
  filter(short_name %in% c("Human population\n(person)",
                           "Shortest dist. to stream\n(m.)",
                           "Degree of clustering of the households\n(NA)",
                           "Distance to the edge of the village\n(meters)",
                           "Surface of crops\n(% of landscape in a 2 km buffer area)")) %>%
  mutate(short_name=gsub("m\\.","meters",short_name)) %>%
  mutate(short_name=gsub("NA","unitless",short_name)) %>%
  mutate(codepays = ifelse(codepays=="CI","Korhogo (IC)","Diébougou (BF)")) %>%
  mutate(codepays = forcats::fct_relevel(codepays,c("Korhogo (IC)","Diébougou (BF)")))

plot_othspa2 <- ggplot(oth_spatial2, aes(y = val, x = short_name,fill=codepays )) +
    geom_boxplot() + 
    facet_wrap(.~short_name, scales = "free") + 
    theme_bw() +
    theme(axis.text.x=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          legend.position = "bottom") + 
  labs(fill = "Study area",caption = 'Boxplots summarize the distribution over all the collection points for the considered study area.') + 
  scale_fill_grey(start=0.3, end=0.7) + 
  ggtitle("Landscape", subtitle = 'Landscape variables for each study area')

ggsave(filename="landscape.png",plot=plot_othspa2,path="/home/ptaconet/phd/articles/article2",dpi = 300)

```

## Micro-climatic conditions

```{r }
env_nightcatch_postedecapture <- dbReadTable(react_gpkg,"env_nightcatch_postedecapture") %>% dplyr::select(-fid)

th_env_nightcatch_postedecapture <- read.csv("/home/ptaconet/Bureau/data_anglique.csv") %>%
  mutate(idpostedecapture = as.character(idpostedecapture)) %>%
  mutate(date_time = lubridate::ymd_hms(date_time)) %>%
  mutate(idpointdecapture = substr(idpostedecapture,1,nchar(idpostedecapture)-1)) %>%
  left_join(periodes_interv %>% dplyr::select(idpointdecapture,codevillage,codepays, nummission)) %>%
  #filter(codepays == code_pays) %>%
  pivot_longer(cols = temperature_hygro:pressure_baro, names_to = "var", values_to = "val") %>%
  mutate(date_time = lubridate::floor_date(date_time,"hour")) %>%
  group_by(codepays,codevillage, nummission, date_time, var) %>%
  summarise(val=mean(val))


th_env_nightcatch_postedecapture2 <- th_env_nightcatch_postedecapture %>%
  group_by(codepays,nummission, var) %>%
  summarise(vale = mean(val),sd = sd(val)) %>%
  filter(var %in% c("humidity_baro","temperature_baro","pressure_baro")) %>%
  mutate(var = case_when(
    var == "humidity_baro" ~ "Humidity (%)",
    var == "temperature_baro" ~ "Temperature (°c)",
    var == "pressure_baro" ~ "Atm. pressure (hpa)"))

plot_2 <- ggplot(th_env_nightcatch_postedecapture2, aes(y = vale, x = as.numeric(nummission) )) +
  geom_line(color = "red") + 
  facet_wrap(.~var, scales = "free") + 
  geom_errorbar(aes(ymin=vale-sd, ymax=vale+sd), width=.1,position=position_dodge(.9)) + theme_bw()

th_env_nightcatch_postedecapture <- th_env_nightcatch_postedecapture %>%
  mutate(hour = lubridate::hour(date_time)) %>%
  group_by(codepays,nummission,hour,var) %>%
  summarise(vale = mean(val), upper = mean(val)+sd(val), lower = mean(val)-sd(val)) %>%
  mutate(date = ifelse(hour < 12, "2000-01-02","2000-01-01")) %>%
  mutate(date = lubridate::ymd_hms(paste0(date," ",hour,":00:00"))) %>%
  filter(upper<10000) %>%
  filter(var %in% c("luminosite_hobo","pressure_baro","temperature_hygro","humidity_hygro")) %>%
  mutate(var = case_when(var=="luminosite_hobo" ~ "Luminosity (lux)",
                         var=="pressure_baro" ~ "Pressure (hPa)",
                         var=="temperature_hygro" ~ "Temperature (°C)",
                         var=="humidity_hygro" ~ "Humidity (%)")) %>%
  mutate(codepays = ifelse(codepays=="CI","IC","BF")) %>%
  mutate(codepays = forcats::fct_relevel(codepays,c("IC","BF"))) %>%
  mutate(entomo_mission="entomological survey")
  
plot_microclimate_bf <- ggplot(th_env_nightcatch_postedecapture %>% filter(codepays=="BF"), aes(x=date, y = vale)) + 
  facet_grid(var~entomo_mission+nummission, scales = "free") +
  geom_ribbon(aes(ymin=lower, ymax=upper), linetype=2, alpha=0.7, fill = "grey70") +
  geom_line(size = 0.2) + 
  scale_x_datetime(labels = date_format("%H"),
                     date_breaks = "2 hours") +
  labs(y = NULL) + 
  labs(x = "hour",title = "Diébougou (BF)") + 
  theme_bw() + 
  theme(strip.text.y = element_text(size = 7))
  

plot_microclimate_ci <- ggplot(th_env_nightcatch_postedecapture %>% filter(codepays=="IC"), aes(x=date, y = vale)) + 
  facet_grid(var~entomo_mission+nummission, scales = "free") +
  geom_ribbon(aes(ymin=lower, ymax=upper), linetype=2, alpha=0.7, fill = "grey70") +
  geom_line(size = 0.2) + 
  scale_x_datetime(labels = date_format("%H"),
                     date_breaks = "2 hours") +
  labs(y = NULL) + 
  labs(x = "hour",title = "Korhogo (IC)") + 
  theme_bw() + 
  theme(strip.text.y = element_text(size = 7))

p <- plot_microclimate_ci / plot_microclimate_bf + plot_annotation(
  title = 'Micro-climate',
  subtitle = 'Micro-climatic conditions during each entomological survey',
  caption = 'Solid bars indicate the mean for all the collection points in the considered entomological survey.\nGrey ribbons indicates the mean ± the standard deviation (i.e. spatial variability).'
) 

ggsave(filename="microclim.png",plot=p,path="/home/ptaconet/phd/articles/article2",dpi = 300)

```